### ISSUE TITLE
fix(NameRegistry): cannot register an fname without an fid during some states

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#110]
### Problem
There is no way to register only an fname when the `IDRegistry.trustedOnly == false` and `NameRegistry.trustedOnly == true`.  We expect this may happen in some small percentage (~10%) of invite scenarios when we launch on mainnet.

The problem emerges because we configure the contracts such that NameRegistry's trusted caller is BundleRegistry and BundleRegistry's trusted caller is the Portal server. Since the BundleRegistry only exposes methods to register both an fid and an fname at once, there is no way for Portal to call the NameRegistry directly and get just an fname. 

### Solutions

There are a few way to work around this and I'm leaning towards Option 1 since it is the most gas efficient and adds a little complexity to BundleRegistry which is reasonably isolated from the other "primary" contracts.

**Option 1: Add a `registerNameOnly` method to BundleRegistry**
Portal can call this method to get an fname. This costs slightly more gas (~3k) than if portal could call the NameRegistry directly for this 10% of cases, and adds a little bit of ongoing complexity. 

**Option 2: Remove BundleRegistry's `trustedRegister` and `partialTrustedRegister`**
Portal must now directly call the NameRegistry and IDRegistry until the final mainnet phase when there are no trusted callers. This increases gas costs for registration by about 18k which is borne by portal during this phase, but dramatically simplifies BundleRegistry. 

**Option 3: Get rid of BundleRegistry**
Revert to a state where there is no BundleRegistry and callers must interact with each contract separately. This simplifies the model in all cases but increases for users and portal by 18k in the scenario when the user wants both an fid and an fname. This decision could be reverted later, it is simple to add a BundleRegistry back at any point.

**Comment by pfletcherhill** [comment]
I think this problem is relevant for testnet too. In order fro the Bundle Registry to work, the trusted caller for both the ID Registry and the Name Registry have to be set to the Bundle Registry's address. But on all networks, the FRS is designed to allow someone to register an fname using a valid invite, even if they already have an fid. And if the Name Registry's trusted caller is the Bundle Registry, the FRS cannot call it directly in that case, which will happen anytime an existing user wants to register a new fname.

My preference would be to get rid of the Bundle Registry for now and consider adding it back later once we have more data about user behavior.

**Comment by varunsrin** [comment]
OK, I think that's reasonable to start without the BundleRegistry. You should be able to get that working by deploying the contracts using their deploy scripts and just ignoring the BundleRegistry script. 

We should clean up and potentially remove the BundleRegistry, but I'll push that out of the current milestone since it is no longer critical.

**Comment by varunsrin** [comment]
Closing since we decided not to ship portal for now.
