### ISSUE TITLE
ci: move from prettier to forge fmt 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#120]
forge [now supports](https://twitter.com/gakonst/status/1566627137502584832) formatting. we should replace prettier with this to reduce our dependency on JS.

**Comment by gaavar** [comment]
Hello! Can I work on this issue?

**Comment by varunsrin** [comment]
all yours!

**Comment by gaavar** [comment]
Update: it seems that the `fmt` tool [documentation](https://book.getfoundry.sh/reference/config/formatter) doesn't contain some flags/features that were recently developed.

One of them is needed to ensure that the function parameters are kept multiline instead of being clubbed together to fit a single line.

I am following up on that with them [here!](https://github.com/foundry-rs/foundry/issues/3713)

**Comment by varunsrin** [comment]
if the function still respects line length, i think its fine to merge for now and make that update later when forge supports it

**Comment by gaavar** [comment]
Hello! I just created a pull request for this issue [here!](https://github.com/farcasterxyz/contracts/pull/160/files)

Requesting feedback!
