### ISSUE TITLE
Require recovery address to be set up when acquiring a new username or id

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#19]
### Rationale

Users should be encouraged to set up a recovery address since this reduces the change of losing their Farcaster identity. 

A number of beta users misplaced their seed phrases. We believe the problem is because users do not value the newly created seed phrase during sign up, when they have not used the network. They often do not take sufficient precaustions to back this up. As they get more active on the platform, the identity becomes more valuable but they almost never go back and increase the security around their seed phrase.  

Our [recovery system](https://github.com/farcasterxyz/protocol#33-recovery) offers a good solution, while maintaining sufficient decentralization. But there are two problems: 

1. It is an optional method, which means that developers who build apps are more likely to not set this up for users. 
2. It requires an additional transaction, which means that users (or developers) must pay more to set this up.  

## Proposal

1. The `register` and `bid` methods will require a recovery address. This makes setting a recovery address cheaper and signals that it's an expected behavior. Users can opt out by setting it to `0x00` and pay a marginally higher gas cost than they would have previously. 

2. The `transferFrom` and `transfer` functions will NOT require a recovery address and reset the recovery to zero whenever they are called. These functions are often called when ownership is changing hands, and we want to ensure that the previous owner does not set their address as the recovery system, since that opens the door to an attack where they can "recovery back" the identity after a sale.  New owners must place another transaction to set up the recovery address. 
 
3. The `setRecoveryAddress` methods are now called `changeRecoveryAddress` which clarifies that there is always a recovery address set (even if it is `0x0000`). 

### Account Registry Changes

Current function calls: 

```solidity
register()
setRecoveryAddress(address recoveryAddress)
```

Proposed functions: 

```solidity
register(address recoveryAddress)
changeRecoveryAddress(address recoveryAddress)
```

### Namespace Changes

Current function calls: 

```solidity
register(bytes16 username, address to, bytes32 secret)
setRecoveryAddress(uint256 tokenId, address recoveryAddress)
 bid(uint256 tokenId)
```

Proposed functions: 

```solidity
register(bytes16 username, address to, bytes32 secret, address recoveryAddress)
changeRecoveryAddress(uint256 tokenId, address recoveryAddress)
 bid(uint256 tokenId, address recoveryAddress)
```

**Comment by pfletcherhill** [comment]
I think this proposal is generally okay with some hesitations...

I don't have a good mental model for how recovery addresses for accounts will differ from recovery addresses for usernames. So I'll talk exclusively about accounts. 

I wonder whether the problems we've experienced in beta will translate to mainnet. My understanding is that we currently generate a new custody address for each user, because we assume users don't want to accidentally associate their account with their existing on-chain identity. Then users lose the seed phrase for the custody address we generated, so we want to increase the number of custody addresses that are secure/backed up.

The proposal here covers one solution—increasing the number of accounts that have a recovery address. But I wonder whether we could achieve the same goal by encouraging new users to make an account using one of their existing Ethereum addresses rather than a newly generated one. Presumably, they've already backed up their main Ethereum address keys.

I'm sure there are privacy-oriented users who would like to use a fresh address for Farcaster, but the current client already makes it hard to preserve privacy by asking you to verify ownership of NFTs. And if you're someone who cares about privacy, you'll want to set your recovery address to another anonymous address (likely as insecure as your custody address) or not set one at all.

My understanding is that the recovery system works well when the recovery address is one that you trust and is more secure than your custody address (i.e. the recovery address is your main Ethereum address or a centralized recovery service). So it seems that forcing new accounts to list a recovery address could reduce privacy and/or increase centralization.

If we assume most users are happy with a less privacy-friendly, more centralized experience, then this proposal will save gas overall (good). Alternatively, if we want to cater to privacy-oriented users, this proposal will likely increase overall gas costs without significantly increasing recoverability (bad) and we should look at other solutions.

**Comment by varunsrin** [comment]
The main reason for using a new address for the Farcaster identity is because it offers the best security model and user experience. If you were to ask users to use their existing Ethereum address to hold their identity from the beginning you run into a few problems when they go through setup: 

1. If the user has a wallet, and must provide this seed phrase to the Farcaster client to create the first delegate, that is a really dangerous security model. 

2. If the user has a wallet, and must sign the delegate right from their wallet, Farcaster client onboardings become difficult since mobile-mobile connections are very finicky.

3.  If the user doesn't have a wallet, they must now set up a separate wallet application and backup their seed phrase securely. 

4. Using your Ethereum wallet does not guarantee that you won't lose your seed phrase. It still happens to people!


A separate address with a recovery system for the identity  allows client to build great experiences without kicking the users between applications, and does not put any of the users other assets in harms way at any point. I also want to point out that: 

1. Setting a recovery address does not increase centralization or reduce privacy and it does not need to be more secure than your primary address. It is just a backup that can move your identity when your custody address is lost. 

2. Setting a recovery address is practically optional as it can be set to the zero address, which is the same as choosing not to set a recovery address. 

3. The gas cost increase is very marginal (a single logic check) which is acceptable if brings with it a large increase in the number of users that have recovery addresses configured.

**Comment by pfletcherhill** [comment]
Got it, understood. Responding to each of the four points about using existing Ethereum addresses:
1. I definitely don't think people should be sharing their Ethereum seed phrase with Farcaster clients. Clients should only have delegate signers in my mind.
2. I was mostly thinking about this case, where I have an existing wallet and want to create a Farcaster account via that wallet. But I didn't consider the difficulty of jumping between mobile apps, so maybe that's more of a desktop activity.
3. It would be optional. A client would let you create an account by (1) signing txs using an existing custody address and third party wallet or (2) create a new address, help you back it up, and pay gas for your account creation tx (i.e. what we do now). 
4. Agreed, but it's more likely that someone has backed up an account that already has reputation than a new one the client generates for them.

Overall, I'm happy with this proposal. All the behavior above is still supported. I imagine I'm more wary of recovery services than the average user—even though I can block an account transfer if I catch it. So like you said, a user like me will set their recovery address to one of their existing Ethereum addresses (paying less gas than they would for two txs) or set it to the zero address (paying a tiny bit more gas than they would otherwise). Both of those are fine outcomes.
