### ISSUE TITLE
bug: slither flags unused return values 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#245]
**What is the bug?**

Likely false positve, see: https://github.com/crytic/slither/issues/2021. Close if we are confident in assessment. 

**How can it be reproduced? (optional)**

Run `slither .`

**Comment by horsefacts** [comment]
This isn't exactly a false positive, since we are ignoring a returned value in both these cases.

Our _sendNative is basically the same as OZ [sendValue](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e50c24f5839db17f46991478384bfda14acfb830/contracts/utils/Address.sol#L64), but we are ignoring the returndata, the second arg in the tuple.

Similarly, we're not using the value of startedAt returned by the price feed, which isn't usually used in ETH price feed validations. For the ETH price feed, I believe this is always equal to updatedAt. I would be OK adding an explanatory comment for each of these and a // slither-disable-next-line if you are.

**Comment by varunsrin** [comment]
sounds good to me

**Comment by horsefacts** [comment]
(Closing this manually. My comment in #252 didn't auto-close)
